/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package home.testing.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import home.testing.model.ProfessionalCodes;

import home.testing.service.ProfessionalCodesLocalServiceUtil;

/**
 * The extended model base implementation for the ProfessionalCodes service. Represents a row in the &quot;IEFP_ProfessionalCodes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfessionalCodesImpl}.
 * </p>
 *
 * @author LMendes
 * @see ProfessionalCodesImpl
 * @see home.testing.model.ProfessionalCodes
 * @generated
 */
public abstract class ProfessionalCodesBaseImpl
	extends ProfessionalCodesModelImpl implements ProfessionalCodes {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a professional codes model instance should use the {@link ProfessionalCodes} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ProfessionalCodesLocalServiceUtil.addProfessionalCodes(this);
		}
		else {
			ProfessionalCodesLocalServiceUtil.updateProfessionalCodes(this);
		}
	}
}