/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package home.testing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ProfessionalCodes service. Represents a row in the &quot;IEFP_ProfessionalCodes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link home.testing.model.impl.ProfessionalCodesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link home.testing.model.impl.ProfessionalCodesImpl}.
 * </p>
 *
 * @author LMendes
 * @see ProfessionalCodes
 * @see home.testing.model.impl.ProfessionalCodesImpl
 * @see home.testing.model.impl.ProfessionalCodesModelImpl
 * @generated
 */
public interface ProfessionalCodesModel extends BaseModel<ProfessionalCodes> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a professional codes model instance should use the {@link ProfessionalCodes} interface instead.
	 */

	/**
	 * Returns the primary key of this professional codes.
	 *
	 * @return the primary key of this professional codes
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this professional codes.
	 *
	 * @param primaryKey the primary key of this professional codes
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the professional codes ID of this professional codes.
	 *
	 * @return the professional codes ID of this professional codes
	 */
	public int getProfessionalCodesId();

	/**
	 * Sets the professional codes ID of this professional codes.
	 *
	 * @param professionalCodesId the professional codes ID of this professional codes
	 */
	public void setProfessionalCodesId(int professionalCodesId);

	/**
	 * Returns the level of this professional codes.
	 *
	 * @return the level of this professional codes
	 */
	public int getLevel();

	/**
	 * Sets the level of this professional codes.
	 *
	 * @param level the level of this professional codes
	 */
	public void setLevel(int level);

	/**
	 * Returns the code of this professional codes.
	 *
	 * @return the code of this professional codes
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this professional codes.
	 *
	 * @param code the code of this professional codes
	 */
	public void setCode(String code);

	/**
	 * Returns the designation of this professional codes.
	 *
	 * @return the designation of this professional codes
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this professional codes.
	 *
	 * @param designation the designation of this professional codes
	 */
	public void setDesignation(String designation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProfessionalCodes professionalCodes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProfessionalCodes> toCacheModel();

	@Override
	public ProfessionalCodes toEscapedModel();

	@Override
	public ProfessionalCodes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}